### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by 0ljik** [wangwenx190/qtlottie#1]
"cmake --install . " doesn't work. I get this:
-- Install configuration: ""

and nothing is changed. Other project's cmake can't find it
OS: ArchLinux

**Comment by wangwenx190** [comment]
This project doesn't support install for now due to I didn't write any install scripts and CMake config scripts. But if you are building it as a sub directory of your project, you can link to it directly using `target_link_libraries(YourApp PRIVATE QtLottie)`. CMake will setup the include directories and library dependencies for your project automatically.

**Comment by 0ljik** [comment]
I have setup as sub directory as you suggested and tested it. All working fine.
Unfortunately, without the ability to stop at a selected frame it doesn't help me.
